name: ebombo

services:
  web:
    image: ebombo-web
    ports:
      - "4100:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://host.docker.internal:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
